package com.bhawana.lms.domain;

public enum LoanAccountStatus {
    PENDING_DISBURSEMENT,
    DISBURSEMENT_REQUESTED,
    DISBURSED,
    CLOSED,
    FORECLOSED,
    DISBURSEMENT_FAILED,
    DISBURSEMENT_PENDING_RECONCILIATION
}
