package com.bhawana.lms.domain;

public enum LspAuditEventAction {
    WEBHOOK_URL_CHANGED,
    WEBHOOK_SECRET_ROTATED,
    WEBHOOK_ENABLED,
    WEBHOOK_DISABLED,
    WEBHOOK_EVENT_TYPES_CHANGED,
    LSP_IP_ALLOWLIST_ENTRY_ADDED,
    LSP_IP_ALLOWLIST_ENTRY_REMOVED
}
