package com.bhawana.lms.domain;

public enum OpsAlertType {
    BORROWER_IDENTITY_CONFLICT,
    BORROWER_ACTIVE_LOAN_DUPLICATE,
    OPS_USER_ESCALATION,
    STALE_INTAKE,
    STUCK_DISBURSEMENT,
    DPD_BUCKET_TRANSITION,
    LSP_AUTO_REJECT_SPIKE,
    WEBHOOK_DEAD_LETTER,
    RATE_LIMIT_BREACH,
    LSP_DISABLED,
    MANUAL_RULE_ENGINE_OVERRIDE,
    LSP_BOUND_VIOLATION,
    BORROWER_BANK_DETAILS_VELOCITY,
    DISBURSEMENT_RETRY_EXHAUSTED
}
