package com.bhawana.lms.domain;

public enum WebhookEventType {
    LOAN_CREATED,
    LOAN_STATUS_CHANGED,
    LOAN_DISBURSEMENT_UPDATED,
    DISBURSEMENT_REQUESTED,
    DISBURSEMENT_COMPLETED,
    DISBURSEMENT_FAILED,
    DOCUMENTS_UPLOADED,
    LOAN_REPAYMENT_RECORDED,
    LOAN_FULLY_REPAID,
    FORECLOSURE_QUOTE_REQUESTED,
    LOAN_FORECLOSURE_COMPLETED
}
