package com.bhawana.lms.service;

/**
 * Typed schedule validation failures for LSP_PROVIDED repayment schedules.
 */
public enum ScheduleViolationType {
    SCHEDULE_OPENING_MISMATCH,
    SCHEDULE_CHAIN_BROKEN,
    SCHEDULE_FINAL_NONZERO,
    SCHEDULE_ROW_RECONCILE_FAILED,
    SCHEDULE_PRINCIPAL_NOT_CLOSED,
    SCHEDULE_INSTALLMENT_COUNT_MISMATCH,
    SCHEDULE_FIRST_DUE_OUT_OF_WINDOW,
    SCHEDULE_CADENCE_VIOLATION,
    SCHEDULE_HORIZON_EXCEEDED,
    SCHEDULE_INTEREST_ROW_MISMATCH,
    SCHEDULE_INTEREST_TOTAL_MISMATCH,
    SCHEDULE_GENERIC
}
