#!/usr/bin/env python3
"""Generate code/PDF-based E2E test matrix (no runtime test results)."""

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

OUTPUT = Path(__file__).resolve().parent.parent / "e2e-test-matrix.xlsx"

REQUIRED_HEADERS = [
    "UC",
    "The use case",
    "Expected behaviour",
    "Pass / Fail",
    "Actual behaviour / Current behaviour",
]

OPTIONAL_HEADERS = [
    "Actor",
    "Module",
    "Source",
    "Test Type",
    "API / Screen Tested",
    "Severity",
    "Notes",
]

HEADERS = REQUIRED_HEADERS + OPTIONAL_HEADERS

NOT_TESTED = "Not Tested"
CODE_PDF = "Code + PDF audit"


def row(
    uc_id,
    title,
    expected,
    actual,
    actor="",
    module="",
    source=CODE_PDF,
    test_type="",
    api_screen="",
    severity="",
    notes="",
):
    return [
        uc_id,
        title,
        expected,
        NOT_TESTED,
        actual,
        actor,
        module,
        source,
        test_type,
        api_screen,
        severity,
        notes,
    ]


USE_CASES = [
    row(
        "UC-001",
        "User Login — valid credentials",
        "User submits username and password; system validates credentials and account status; establishes JWT session and redirects to role-appropriate home page.",
        "Implemented: POST /api/v1/auth/login returns accessToken + refresh cookie. Frontend LoginPage at /login with role presets (ops.admin, ops.reviewer1, etc.). SYSTEM_ADMIN → /home; OPS_USER → /loan-applications; LSP_UI → /my-loans.",
        "Any human user",
        "Authentication",
        test_type="Happy path",
        api_screen="POST /api/v1/auth/login; /login",
    ),
    row(
        "UC-001-EC",
        "User Login — invalid credentials",
        "System rejects login with clear error; no session created; failed attempt auditable.",
        "Implemented in AuthController + auth audit service. Rate limiting referenced in PDF Workflow 4; verify AuthAuditService records failures.",
        "Any human user",
        "Authentication",
        test_type="Negative",
        api_screen="POST /api/v1/auth/login",
        severity="Medium",
    ),
    row(
        "UC-002",
        "Mandatory Password Change",
        "After login when passwordChangeRequired=true, user is redirected to /change-password; must set password meeting policy (12–128 chars); then proceeds to landing page.",
        "Implemented: login response includes passwordChangeRequired; POST /api/v1/auth/password; ChangePasswordPage at /change-password. UserAdminController reset-password sets temp password flag.",
        "Authenticated user",
        "Authentication",
        test_type="Happy path",
        api_screen="/change-password; POST /api/v1/auth/password",
    ),
    row(
        "UC-003",
        "Session Refresh and Logout",
        "Refresh renews access token via refresh cookie without re-login; logout invalidates refresh token and ends session.",
        "Implemented: POST /api/v1/auth/refresh (cookie lms-refresh), POST /api/v1/auth/logout. Frontend auth-api.ts calls both.",
        "Any signed-in user",
        "Authentication",
        test_type="Happy path",
        api_screen="POST /api/v1/auth/refresh; POST /api/v1/auth/logout",
    ),
    row(
        "UC-004",
        "API Client Token Issuance",
        "Partner submits client_id + client_secret; system validates active client and LSP; returns short-lived JWT scoped to tenant.",
        "Implemented: POST /api/v1/auth/token (client credentials grant). ApiClientJwtSessionValidator enforces LSP tenant. IP allowlist checked when enforcement enabled.",
        "LSP API Client",
        "Authentication",
        test_type="Happy path",
        api_screen="POST /api/v1/auth/token",
    ),
    row(
        "UC-005",
        "View Session Context",
        "Signed-in user sees identity, roles, and LSP association (if applicable).",
        "Implemented: GET /api/v1/internal/system/context. Frontend bootstraps session on load. RoleScopeBadge shows context in shell.",
        "Any authenticated user",
        "Authentication",
        test_type="Happy path",
        api_screen="GET /api/v1/internal/system/context",
    ),
    row(
        "UC-006",
        "Create LSP Tenant",
        "Administrator creates LSP with name/code; tenant record created and available for further setup.",
        "Implemented: POST /api/v1/internal/admin/lsps (SYSTEM_ADMIN). UI: /lsps page with create dialog (LspsPage).",
        "System Administrator",
        "Platform Admin",
        test_type="Happy path",
        api_screen="POST /api/v1/internal/admin/lsps; /lsps",
    ),
    row(
        "UC-007",
        "Activate or Deactivate LSP",
        "Administrator changes LSP status; on deactivation API clients deactivated and partner operations blocked; ops alert may fire.",
        "Implemented: PUT /api/v1/internal/admin/lsps/{id}/status. UI status change dialog on /lsps. PDF notes in-flight loan behaviour needs business clarification.",
        "System Administrator",
        "Platform Admin",
        test_type="Happy path",
        api_screen="PUT .../lsps/{id}/status; /lsps",
        notes="PDF Workflow 2: in-flight loan behaviour at deactivation unclear.",
    ),
    row(
        "UC-008",
        "Configure LSP Webhook Subscription",
        "Administrator sets webhook endpoint URL and signing secret; future domain events queued for delivery.",
        "Implemented: PUT /api/v1/internal/admin/lsps/{id}/webhook-subscription. UI on LSP detail in /lsps.",
        "System Administrator",
        "Webhooks",
        test_type="Happy path",
        api_screen="PUT .../webhook-subscription; /lsps",
    ),
    row(
        "UC-009",
        "Manage LSP IP Allowlists",
        "Administrator maintains API and UI IP allowlist entries; enables/disables enforcement per surface.",
        "Implemented: GET/POST/DELETE .../api-ip-allowlist and .../ui-ip-allowlist; GET/PUT .../allowlist-enforcement. UI in LSP admin detail.",
        "System Administrator",
        "Platform Admin",
        test_type="Happy path",
        api_screen="/lsps; allowlist admin APIs",
    ),
    row(
        "UC-010",
        "Create Internal or LSP User",
        "Administrator provisions user with role(s) and LSP scope; account created (often with temp password).",
        "Implemented: POST /api/v1/internal/admin/users. UI: /users create dialog with TempPasswordRevealCard.",
        "System Administrator",
        "User Admin",
        test_type="Happy path",
        api_screen="POST /api/v1/internal/admin/users; /users",
    ),
    row(
        "UC-011",
        "Update User or Reset Password",
        "Administrator updates user attributes or resets password; user can sign in with updated credentials.",
        "Implemented: PUT /api/v1/internal/admin/users/{id}; POST .../reset-password; POST .../revoke-sessions. UI edit/reset/revoke on /users.",
        "System Administrator",
        "User Admin",
        test_type="Happy path",
        api_screen="/users; user admin APIs",
    ),
    row(
        "UC-012",
        "Create API Client",
        "Administrator creates machine credentials for LSP; client_id and secret shown once.",
        "Implemented: POST /api/v1/internal/admin/api-clients. UI: /api-clients with secret reveal on create.",
        "System Administrator",
        "API Clients",
        test_type="Happy path",
        api_screen="POST /api/v1/internal/admin/api-clients; /api-clients",
    ),
    row(
        "UC-013",
        "Rotate API Client Secret",
        "Administrator rotates secret; new secret issued; partner updates integration.",
        "Implemented: POST /api/v1/internal/admin/api-clients/{id}/rotate-secret. UI RotateSecretDialog on /api-clients. No edit name/status in UI.",
        "System Administrator",
        "API Clients",
        test_type="Happy path",
        api_screen="POST .../rotate-secret; /api-clients",
    ),
    row(
        "UC-014",
        "Create or Update Loan Product",
        "Administrator defines product with amount/tenure/rate bounds; product saved active or inactive.",
        "Implemented: POST/PUT /api/v1/internal/admin/products. UI: /products create and edit dialogs. Roles: SYSTEM_ADMIN, PRODUCT_ADMIN.",
        "System Administrator, Product Administrator",
        "Products",
        test_type="Happy path",
        api_screen="/products; product admin APIs",
    ),
    row(
        "UC-015",
        "Configure Product–LSP Mappings",
        "Administrator maps products to LSPs; only active mapped products available for origination.",
        "Implemented: PUT /api/v1/internal/admin/products/{id}/mappings and product-lsp-mappings endpoints. UI LspMultiSelect on product detail.",
        "System Administrator, Product Administrator",
        "Products",
        test_type="Happy path",
        api_screen="/products; mapping APIs",
    ),
    row(
        "UC-016",
        "LSP API — Create Loan Application",
        "Partner authenticates and submits application; system validates, deduplicates borrower by PAN, creates checklist, runs auto-approval, returns application ID and status.",
        "Implemented: POST /api/v1/lsp/loan-applications (LSP_API_CLIENT only). LoanAutoApprovalGateService triggers when 8 intake docs complete. Idempotency via LspApiIdempotencyService. ADR: origination is API-only (no LSP UI create).",
        "LSP API Client",
        "Origination",
        source="PDF + ADR 0003",
        test_type="Happy path",
        api_screen="POST /api/v1/lsp/loan-applications",
    ),
    row(
        "UC-017",
        "Operations — Create Loan Application",
        "Staff manually enters loan from operations console; same lifecycle as API intake.",
        "Backend implemented: POST /api/v1/internal/ops/loan-applications (SYSTEM_ADMIN, OPS_USER). PDF and docs note NO dedicated UI create dialog in frontend — API-only from ops perspective.",
        "System Administrator, Operations User",
        "Origination",
        test_type="Happy path",
        api_screen="POST /api/v1/internal/ops/loan-applications",
        notes="GAP: PDF Workflow 11 — no frontend create form; ops intake via API only.",
        severity="Medium",
    ),
    row(
        "UC-018",
        "Auto-Approval Rule Evaluation",
        "On awaiting approval, engine checks product/LSP/mapping active, amount/tenure/rate bounds, borrower fields, required documents, no open loan; pass → approved pending disbursal; fail → rejected with reason codes.",
        "Implemented: LoanAutoApprovalRuleEngine with 8 rules (PRODUCT_INACTIVE, LSP_INACTIVE, LSP_PRODUCT_MAPPING_INACTIVE, LOAN_AMOUNT_OUT_OF_RANGE, LOAN_TENURE_OUT_OF_RANGE, BORROWER_REQUIRED_FIELDS_MISSING, REQUIRED_DOCUMENTS_NOT_UPLOADED, BORROWER_HAS_OPEN_LOAN). Requires all 8 doc types for gate trigger.",
        "System",
        "Origination",
        test_type="System / automated",
        api_screen="Internal service; triggered post-intake",
    ),
    row(
        "UC-019",
        "Upload KYC Documents (LSP)",
        "Partner uploads documents for checklist types; system stores and marks checklist submitted.",
        "Implemented: POST multipart /api/v1/lsp/loan-applications/{id}/documents and /documents/batch (LSP_API_CLIENT, LSP_UI_WRITE). UI: /my-loans/{id} document upload. 8 required types: PAN_CARD, AADHAAR_FILE, ADDRESS_PROOF, INCOME_PROOF, BANK_STATEMENT, SELFIE_PHOTOGRAPH, KFS, LOAN_AGREEMENT.",
        "LSP API Client, LSP UI Write",
        "Documents",
        test_type="Happy path",
        api_screen="/my-loans/{id}; LSP document APIs",
    ),
    row(
        "UC-020",
        "Download KYC Documents (Operations)",
        "Authorized staff downloads KYC from loan detail; access logged for compliance.",
        "Implemented: GET .../kyc-documents/{type}/content and download-all ZIP. UI DocumentsTab on /loan-applications/{id}. Document access audit via document-access-audits endpoint.",
        "System Administrator, Operations User",
        "Documents",
        test_type="Happy path",
        api_screen="/loan-applications/{id}; ops KYC APIs",
    ),
    row(
        "UC-021",
        "Manual Status Transition",
        "Administrator selects permitted target status with justification; system validates state machine; updates application and audit; webhook when applicable.",
        "Implemented: POST .../status-transitions (SYSTEM_ADMIN, OPS_USER per controller — but UI ActionBar gates LOAN_STATUS_UPDATE: OPS has permission in permissions.ts but PDF says admin only for manual transitions; UI shows ActionBar for SYSTEM_ADMIN and PRODUCT_ADMIN, not OPS). State machine in LoanApplicationStatus.canTransitionTo().",
        "System Administrator",
        "Status Admin",
        test_type="Happy path",
        api_screen="POST .../status-transitions; ActionBar",
        notes="GAP: OPS_USER has LOAN_STATUS_UPDATE in frontend permissions but PDF assigns manual transition to admin; OPS gets escalate-only in UI.",
    ),
    row(
        "UC-022",
        "Manual Status Override",
        "Administrator overrides status bypassing normal transitions with reason code; fully audited.",
        "Implemented: POST .../manual-status (SYSTEM_ADMIN only). UI fallback when standard transition fails.",
        "System Administrator",
        "Status Admin",
        test_type="Happy path",
        api_screen="POST .../manual-status",
    ),
    row(
        "UC-023",
        "Invalidate Loan (Pre-Disbursal)",
        "Partner invalidates in-flight application from pre-disbursal statuses; moves to INVALID terminal; webhook queued.",
        "Implemented: POST /api/v1/lsp/loan-applications/{id}/invalid (LSP_UI_WRITE only in controller — API invalidate may differ). Pre-disbursal: INITIALIZED, AWAITING_APPROVAL, APPROVED_PENDING_DISBURSAL, DISBURSEMENT_RETRY. UI mark-invalid dialog on /my-loans/{id}.",
        "LSP API Client, LSP UI Write",
        "Origination",
        test_type="Happy path",
        api_screen="POST .../invalid; /my-loans/{id}",
        notes="Verify LSP_API_CLIENT invalidate path — controller annotation is LSP_UI_WRITE only on invalid endpoint.",
    ),
    row(
        "UC-024",
        "Submit Repayment Schedule",
        "Partner submits installment schedule for approved application; validated and stored for disbursement and servicing.",
        "Implemented: PUT /api/v1/lsp/loan-applications/{id}/repayment-schedule (LSP_API_CLIENT). LoanRepaymentScheduleService validates principal/interest math.",
        "LSP API Client",
        "Disbursement",
        test_type="Happy path",
        api_screen="PUT .../repayment-schedule",
    ),
    row(
        "UC-025",
        "Disbursement Bank Check",
        "Partner triggers bank verification; mismatches logged for ops follow-up.",
        "Implemented: POST /api/v1/lsp/loan-applications/{id}/disbursement-bank-check. LoanDisbursementService compares account/IFSC to borrower on file.",
        "LSP API Client",
        "Disbursement",
        test_type="Happy path",
        api_screen="POST .../disbursement-bank-check",
    ),
    row(
        "UC-026",
        "Initiate Disbursement",
        "Administrator triggers disbursement when prerequisites met; outcome updates loan status.",
        "Implemented: POST .../disbursement-requests (SYSTEM_ADMIN only). UI DisbursementInitiateDialog; client-side isSystemAdmin() gate.",
        "System Administrator",
        "Disbursement",
        test_type="Happy path",
        api_screen="POST .../disbursement-requests; loan detail",
    ),
    row(
        "UC-027",
        "Automated Disbursement Processing",
        "Scheduled worker processes APPROVED_PENDING_DISBURSAL and DISBURSEMENT_RETRY; validates docs/schedule/bank; success → DISBURSED; retryable failure → DISBURSEMENT_RETRY; exhaustion → alert/reject.",
        "Implemented: LoanDisbursementWorkerService. Configurable via application properties. On validation failure may reject via WORKER context.",
        "System",
        "Disbursement",
        test_type="System / automated",
        api_screen="Background worker",
    ),
    row(
        "UC-028",
        "Simulate Disbursement Outcome",
        "In test environments, admin submits mock disbursement outcome.",
        "Implemented: POST .../disbursement-requests/mock-outcome (SYSTEM_ADMIN). Dev/test capability.",
        "System Administrator",
        "Disbursement",
        test_type="Happy path",
        api_screen="POST .../mock-outcome",
    ),
    row(
        "UC-029",
        "Record Payment (Internal Operations)",
        "Staff records full installment payment; partial not accepted; allocates to next pending; may advance DISBURSED → UNDER_REPAYMENT; all paid → CLOSED.",
        "Implemented: POST .../payments (SYSTEM_ADMIN per controller annotation). UI RepaymentsTab with canPostRepayment for SYSTEM_ADMIN and OPS_USER. GAP: controller says SYSTEM_ADMIN only but UI allows OPS_USER — verify backend PreAuthorize.",
        "System Administrator, Operations User",
        "Servicing",
        test_type="Happy path",
        api_screen="POST .../payments; RepaymentsTab",
        notes="Potential role mismatch: UI allows OPS payment post; verify controller @PreAuthorize.",
        severity="High",
    ),
    row(
        "UC-030",
        "Record Payment (LSP API)",
        "Partner posts payment with duplicate protection; same rules as internal ops.",
        "Implemented: POST /api/v1/lsp/loans/{loanId}/payments (LSP_API_CLIENT). Idempotency key required. Exact installment amount enforced in LoanRepaymentCommandService.",
        "LSP API Client",
        "Servicing",
        test_type="Happy path",
        api_screen="POST /api/v1/lsp/loans/{id}/payments",
    ),
    row(
        "UC-031",
        "Request Foreclosure Quote",
        "Actor requests quote; system calculates payoff and validity.",
        "Implemented: POST .../foreclosure-quotes (ops, SYSTEM_ADMIN); POST /api/v1/lsp/loans/{id}/foreclosure-quote (LSP_API_CLIENT, LSP_UI_WRITE). LoanForeclosureCommandService.",
        "System Administrator, LSP API Client",
        "Servicing",
        test_type="Happy path",
        api_screen="Foreclosure quote APIs",
    ),
    row(
        "UC-032",
        "Execute Foreclosure",
        "Administrator executes against valid quote; loan → FORECLOSED terminal.",
        "Implemented: POST .../foreclosure-quotes/{quoteId}/execute (SYSTEM_ADMIN ops); LSP path also has execute on LspLoanApiController. UI ForeclosureSummaryCard for admin.",
        "System Administrator",
        "Servicing",
        test_type="Happy path",
        api_screen="Foreclosure execute APIs; loan detail",
    ),
    row(
        "UC-033",
        "Update Borrower Bank Details",
        "Actor submits updated bank info; validated, persisted, audited.",
        "Implemented: PATCH /api/v1/lsp/borrowers/{id}/bank-details (LSP_API_CLIENT); PATCH /api/v1/internal/admin/borrowers/{id}/bank-details (SYSTEM_ADMIN).",
        "LSP API Client, System Administrator",
        "Borrower",
        test_type="Happy path",
        api_screen="Borrower bank-details APIs",
    ),
    row(
        "UC-034",
        "Search and View Borrowers",
        "Staff searches by PAN/name; views profile and linked loans.",
        "Implemented: GET /api/v1/internal/admin/borrowers with q and pagination. UI /borrowers and /borrowers/{id}. Read-only — no edit in UI.",
        "System Administrator, Operations User, Product Administrator",
        "Operations",
        test_type="Happy path",
        api_screen="/borrowers; borrower admin APIs",
    ),
    row(
        "UC-035",
        "View Portfolio Dashboard",
        "Administrator sees aggregated portfolio metrics on home.",
        "Implemented: GET /api/v1/internal/home/overview (SYSTEM_ADMIN). UI /home — page redirects non-admin users. KPI strip, DPD buckets, recent applications.",
        "System Administrator",
        "Operations",
        test_type="Happy path",
        api_screen="/home; GET .../home/overview",
    ),
    row(
        "UC-036",
        "Search Loan Applications",
        "User filters loan list by status, LSP, dates, etc.; opens detail.",
        "Implemented: GET /api/v1/internal/ops/loan-applications with filters (lspId, productId, status, q, lspLoanId, bhawLoanId, disbursalDateFrom/To, pagination). UI /loan-applications with URL state filters.",
        "Internal roles",
        "Operations",
        test_type="Happy path",
        api_screen="/loan-applications",
    ),
    row(
        "UC-037",
        "Portfolio MIS — Preview and Sync Download",
        "Administrator previews or synchronously downloads MIS for date range.",
        "Implemented: GET /api/v1/internal/reports/portfolio-mis/preview, /summary, and sync CSV download. UI /reports preview tab.",
        "System Administrator",
        "Reporting",
        test_type="Happy path",
        api_screen="/reports; portfolio-mis APIs",
    ),
    row(
        "UC-038",
        "Async MIS Report Generation",
        "Administrator queues report job; downloads when complete; optional email.",
        "Implemented: POST /api/v1/internal/reports/portfolio-mis/requests; GET /requests; GET /requests/{id}/download. UI reports request queue.",
        "System Administrator",
        "Reporting",
        test_type="Happy path",
        api_screen="/reports; async report APIs",
    ),
    row(
        "UC-039",
        "Acknowledge Operations Alert",
        "Staff acknowledges alert with optional note; status updates.",
        "Implemented: POST /api/v1/internal/alerts/{id}/acknowledge. UI /alerts. SYSTEM_ADMIN and OPS_USER.",
        "System Administrator, Operations User",
        "Alerting",
        test_type="Happy path",
        api_screen="/alerts",
    ),
    row(
        "UC-040",
        "Escalate Loan to Administrator",
        "Ops user escalates loan; system creates admin escalation alert.",
        "Implemented: POST /api/v1/internal/alerts/escalate. UI EscalateToAdminDialog on loan detail (OPS_USER).",
        "Operations User",
        "Alerting",
        test_type="Happy path",
        api_screen="Escalate dialog; POST /alerts/escalate",
    ),
    row(
        "UC-041",
        "Scheduled Alert Rule Evaluation",
        "System evaluates alert rules on schedule; creates/updates ops alerts.",
        "Implemented: alert rules seeded in V60__alert_rules.sql; scheduled evaluation via worker. Rules panel read-only on /alerts for SYSTEM_ADMIN.",
        "System",
        "Alerting",
        test_type="System / automated",
        api_screen="Background scheduler",
    ),
    row(
        "UC-042",
        "Webhook Outbox Dispatch",
        "System delivers signed payloads with retry; transient vs permanent failure classification.",
        "Implemented: webhook outbox worker; POST /api/v1/internal/admin/webhook-outbox/dispatch for manual dispatch.",
        "System",
        "Webhooks",
        test_type="System / automated",
        api_screen="Webhook worker; admin dispatch API",
    ),
    row(
        "UC-043",
        "Manual Webhook Redrive",
        "Administrator redrives permanently failed webhook events.",
        "Implemented: POST /api/v1/internal/admin/webhook-outbox/{id}/redrive. Admin UI via webhook events on loan detail and webhook admin (verify full admin list UI).",
        "System Administrator",
        "Webhooks",
        test_type="Happy path",
        api_screen="Webhook redrive API",
    ),
    row(
        "UC-044",
        "Audit Explorer Search",
        "Administrator searches unified audit timeline across domains.",
        "Implemented: GET /api/v1/internal/admin/audit-events with filters. UI /audit with stream filters and detail sheet.",
        "System Administrator",
        "Audit",
        test_type="Happy path",
        api_screen="/audit",
    ),
    row(
        "UC-045",
        "Auth Audit Search",
        "Administrator queries authentication events (login success/failure).",
        "Implemented: GET /api/v1/internal/ops/auth-audit (SYSTEM_ADMIN). PDF notes no dedicated UI — API only, no frontend route found.",
        "System Administrator",
        "Audit",
        test_type="Happy path",
        api_screen="GET /api/v1/internal/ops/auth-audit",
        notes="GAP: API exists; no dedicated UI screen in frontend router.",
        severity="Low",
    ),
    row(
        "UC-046",
        "LSP View Own Loans",
        "LSP user views tenant-scoped loan list and detail; no cross-tenant access.",
        "Implemented: GET /api/v1/lsp/loan-applications. UI /my-loans and /my-loans/{id}. Tenant isolation via JWT lspId + PostgreSQL RLS on tenant datasource.",
        "LSP UI Read, LSP UI Write",
        "LSP Self-Service",
        test_type="Happy path",
        api_screen="/my-loans",
    ),
    row(
        "UC-047",
        "View LSP Product Catalog",
        "Partner sees active products mapped to their LSP with terms/bounds.",
        "Implemented: GET /api/v1/lsp/products. No dedicated LSP UI catalog page found — API for LSP_API_CLIENT; LSP UI users may not have catalog screen.",
        "LSP API Client, LSP UI User",
        "LSP Self-Service",
        test_type="Happy path",
        api_screen="GET /api/v1/lsp/products",
        notes="GAP: No /my-loans or separate UI page for product catalog; API-only for partners.",
        severity="Low",
    ),
    row(
        "UC-048",
        "Product Administrator — product catalog management (code-discovered)",
        "PRODUCT_ADMIN can create/edit products and mappings but not access admin-only areas.",
        "Implemented: role PRODUCT_ADMIN in router guards for /products; permissions PRODUCT_READ/WRITE + LOAN_READ only. Loan detail ActionBar visible but lifecycle buttons disabled (no LOAN_STATUS_UPDATE).",
        "Product Administrator",
        "Products",
        source="Code audit only",
        test_type="Happy path",
        api_screen="/products",
        notes="Not in PDF index; discovered from role-gates and permissions.ts.",
    ),
    row(
        "UC-049",
        "View loan webhook delivery history on loan detail (code-discovered)",
        "Internal user views webhook delivery attempts for a loan application.",
        "Implemented: GET .../webhook-events on loan detail. Webhooks tab in loan application detail page.",
        "System Administrator, Operations User",
        "Webhooks",
        source="Code audit only",
        test_type="Happy path",
        api_screen="/loan-applications/{id} Webhooks tab",
    ),
    row(
        "UC-050",
        "Revoke user sessions (code-discovered)",
        "Administrator forcibly ends all sessions for a user.",
        "Implemented: POST /api/v1/internal/admin/users/{id}/revoke-sessions. UI action on /users.",
        "System Administrator",
        "User Admin",
        source="Code audit only",
        test_type="Happy path",
        api_screen="/users",
    ),
]

EDGE_CASES = [
    row(
        "EC-001",
        "Login with empty username or password",
        "400 validation error; no token issued.",
        "DTO LoginRequest: @NotBlank on username and password. GlobalExceptionHandler returns structured INVALID_REQUEST.",
        "Any user",
        "Authentication",
        test_type="Validation",
        api_screen="POST /api/v1/auth/login",
        severity="Low",
    ),
    row(
        "EC-002",
        "API token request with invalid client secret",
        "401/403; no access token; auth audit event.",
        "ApiClientAuthenticationService validates credentials. Expected rejection — not runtime verified.",
        "LSP API Client",
        "Authentication",
        test_type="Auth negative",
        api_screen="POST /api/v1/auth/token",
        severity="High",
    ),
    row(
        "EC-003",
        "API call without Authorization header",
        "401 Unauthorized on protected endpoints.",
        "SecurityConfig requires authentication for /api/v1/internal/** and /api/v1/lsp/**.",
        "Any API caller",
        "Authentication",
        test_type="Auth negative",
        api_screen="All protected APIs",
        severity="High",
    ),
    row(
        "EC-004",
        "Expired or malformed JWT",
        "401; request rejected.",
        "JwtDecoder validation in SecurityConfig filter chain.",
        "Any API caller",
        "Authentication",
        test_type="Auth negative",
        severity="High",
    ),
    row(
        "EC-005",
        "LSP API access from IP not on allowlist when enforcement enabled",
        "Request blocked when enforceApi=true and client IP not in CIDR list.",
        "LspSurfaceIpAllowlistService checked at token issuance and request time.",
        "LSP API Client",
        "Platform Admin",
        test_type="Auth negative",
        api_screen="POST /api/v1/auth/token; LSP APIs",
        severity="High",
    ),
    row(
        "EC-006",
        "LSP UI login from IP not on UI allowlist when enforcement enabled",
        "Login blocked for LSP UI users from disallowed IP.",
        "AuthController login flow checks LSP UI allowlist via lspSurfaceIpAllowlistService.",
        "LSP UI User",
        "Authentication",
        test_type="Auth negative",
        severity="High",
    ),
    row(
        "EC-007",
        "OPS_USER attempts to access /reports or /audit via direct URL",
        "403 Permission Denied or redirect; no data exposed.",
        "Route guards: RequireRole SYSTEM_ADMIN_ONLY on /reports and /audit.",
        "Operations User",
        "Authorization",
        test_type="Permission",
        api_screen="/reports; /audit",
        severity="Medium",
    ),
    row(
        "EC-008",
        "PRODUCT_ADMIN attempts disbursement or manual override",
        "Action disabled or 403; insufficient DISBURSEMENT_TRIGGER / LOAN_STATUS_UPDATE.",
        "permissions.ts: PRODUCT_ADMIN lacks DISBURSEMENT_TRIGGER, FORECLOSURE_TRIGGER, LOAN_STATUS_UPDATE. Backend @PreAuthorize should also block.",
        "Product Administrator",
        "Authorization",
        test_type="Permission",
        severity="Medium",
    ),
    row(
        "EC-009",
        "LSP_UI_READ attempts document upload or mark invalid",
        "403 from API; UI may still show buttons (gap).",
        "Controller: document upload requires LSP_UI_WRITE or LSP_API_CLIENT. Frontend my-loans does not hide write controls for READ role — PDF/code gap.",
        "LSP UI Read",
        "Authorization",
        test_type="Permission",
        api_screen="/my-loans/{id}",
        notes="UI gap: write actions visible to READ role.",
        severity="Medium",
    ),
    row(
        "EC-010",
        "Cross-LSP loan application access via LSP API",
        "404 or LSP_BOUND_VIOLATION; no data from other tenant.",
        "LoanApplicationService scopes by authenticated LSP ID; tenant datasource RLS.",
        "LSP API Client",
        "Data isolation",
        test_type="Security",
        severity="Critical",
    ),
    row(
        "EC-011",
        "Cross-LSP loan access via internal ops API with wrong lspId filter",
        "Internal users see all LSPs; filter is user-controlled not a security boundary for admins.",
        "By design: SYSTEM_ADMIN/OPS have ALL_LSP_VIEW. Isolation is partner-side not internal-side.",
        "Internal user",
        "Data isolation",
        test_type="Security",
        severity="Low",
    ),
    row(
        "EC-012",
        "Create loan with duplicate external loan ID for same LSP",
        "409 conflict or validation error; duplicate prevented.",
        "LoanApplicationLifecycleService duplicate external loan ID check referenced in service layer.",
        "LSP API Client",
        "Origination",
        test_type="Duplicate",
        api_screen="POST /api/v1/lsp/loan-applications",
        severity="High",
    ),
    row(
        "EC-013",
        "Create loan with unmapped or inactive product",
        "Rejection with PRODUCT_INACTIVE or LSP_PRODUCT_MAPPING_INACTIVE rule.",
        "Auto-approval rule engine + create validation.",
        "LSP API Client",
        "Origination",
        test_type="Validation",
        severity="High",
    ),
    row(
        "EC-014",
        "Create loan with amount outside product min/max",
        "Auto-reject with LOAN_AMOUNT_OUT_OF_RANGE.",
        "LoanAutoApprovalRuleEngine rule LOAN_AMOUNT_OUT_OF_RANGE.",
        "LSP API Client",
        "Origination",
        test_type="Boundary",
        severity="High",
    ),
    row(
        "EC-015",
        "Create loan for borrower with existing open loan across LSPs",
        "Auto-reject with BORROWER_HAS_OPEN_LOAN.",
        "Global borrower dedup by PAN; open loan check across all LSPs.",
        "LSP API Client",
        "Origination",
        test_type="Business rule",
        severity="Critical",
    ),
    row(
        "EC-016",
        "Create loan with invalid PAN format",
        "400 validation error before business logic.",
        "LspLoanApplicationRequest PAN pattern validation in controller DTO.",
        "LSP API Client",
        "Origination",
        test_type="Validation",
        severity="Medium",
    ),
    row(
        "EC-017",
        "Create loan with missing required borrower fields",
        "Validation error at intake or auto-reject BORROWER_REQUIRED_FIELDS_MISSING.",
        "DTO + auto-approval rule.",
        "LSP API Client",
        "Origination",
        test_type="Validation",
        severity="Medium",
    ),
    row(
        "EC-018",
        "Auto-approval with incomplete document checklist",
        "Gate does not fire until all 8 intake docs submitted; if forced to AWAITING_APPROVAL without docs → REJECTED REQUIRED_DOCUMENTS_NOT_UPLOADED.",
        "LoanAutoApprovalGateService requires 8 document types complete before trigger.",
        "System",
        "Origination",
        test_type="Business rule",
        severity="High",
    ),
    row(
        "EC-019",
        "Invalid status transition (e.g. CLOSED → DISBURSED)",
        "400/422; transition rejected by state machine.",
        "LoanApplicationStatus.canTransitionTo() returns false for terminal states.",
        "System Administrator",
        "Status Admin",
        test_type="State machine",
        severity="High",
    ),
    row(
        "EC-020",
        "Invalidate loan after disbursement",
        "Rejected; INVALID only from pre-disbursal statuses.",
        "isPreDisbursal() gate on invalidate endpoint.",
        "LSP UI Write",
        "Origination",
        test_type="State machine",
        severity="High",
    ),
    row(
        "EC-021",
        "Disbursement without repayment schedule",
        "Disbursement blocked; worker validation fails.",
        "LoanDisbursementWorkerService validatePersistedScheduleForDisbursement.",
        "System",
        "Disbursement",
        test_type="Prerequisite",
        severity="High",
    ),
    row(
        "EC-022",
        "Disbursement without required LMS-managed documents",
        "Disbursement blocked or worker rejects application.",
        "Worker pre-flight document validation in LoanDisbursementService.",
        "System",
        "Disbursement",
        test_type="Prerequisite",
        severity="High",
    ),
    row(
        "EC-023",
        "Disbursement bank check mismatch",
        "Mismatch logged; disbursement may be blocked until resolved.",
        "LoanDisbursementService bank check compares submitted vs on-file details.",
        "LSP API Client",
        "Disbursement",
        test_type="Business rule",
        severity="High",
    ),
    row(
        "EC-024",
        "Disbursement retry exhaustion",
        "Application stays in DISBURSEMENT_RETRY or moves to rejected; ops alert raised.",
        "LoanDisbursementWorkerService retry limit configuration.",
        "System",
        "Disbursement",
        test_type="Failure handling",
        severity="High",
    ),
    row(
        "EC-025",
        "Partial installment payment",
        "Rejected; full installment amount required.",
        "LoanRepaymentCommandService: payment must exactly match installment outstanding.",
        "Operations User, LSP API Client",
        "Servicing",
        test_type="Business rule",
        severity="High",
    ),
    row(
        "EC-026",
        "Duplicate payment idempotency key",
        "Same response as original or idempotency conflict error.",
        "LspApiIdempotencyService fingerprint conflict detection.",
        "LSP API Client",
        "Servicing",
        test_type="Idempotency",
        severity="Medium",
    ),
    row(
        "EC-027",
        "Payment on loan not in DISBURSED or UNDER_REPAYMENT",
        "Rejected with eligibility error.",
        "LoanRepaymentCommandService eligibility check.",
        "LSP API Client",
        "Servicing",
        test_type="State machine",
        severity="High",
    ),
    row(
        "EC-028",
        "Foreclosure execute with expired quote",
        "Rejected; quote must be ACTIVE.",
        "LoanForeclosureCommandService quote validity check.",
        "System Administrator",
        "Servicing",
        test_type="Business rule",
        severity="Medium",
    ),
    row(
        "EC-029",
        "Foreclosure quote on pre-disbursement application",
        "Rejected; only DISBURSED or UNDER_REPAYMENT eligible.",
        "LoanForeclosureCommandService status check.",
        "LSP API Client",
        "Servicing",
        test_type="State machine",
        severity="Medium",
    ),
    row(
        "EC-030",
        "Deactivate LSP with in-flight applications",
        "New origination blocked; behaviour of in-flight loans unclear per PDF.",
        "PDF Workflow 2 marks as Needs Clarification. Code deactivates API clients.",
        "System Administrator",
        "Platform Admin",
        test_type="Business rule",
        notes="Business rule gap in PDF.",
        severity="Medium",
    ),
    row(
        "EC-031",
        "Malformed JSON request body",
        "400 INVALID_REQUEST with correlation ID.",
        "GlobalExceptionHandler; evidenced pattern in tmp-login.json error shape.",
        "Any API caller",
        "API consistency",
        test_type="Validation",
        severity="Low",
    ),
    row(
        "EC-032",
        "Empty request body on POST endpoints",
        "400 validation error.",
        "Jakarta @Valid on controller request bodies.",
        "Any API caller",
        "API consistency",
        test_type="Validation",
        severity="Low",
    ),
    row(
        "EC-033",
        "Invalid UUID in path parameter",
        "400 bad request.",
        "Spring path variable type conversion.",
        "Any API caller",
        "API consistency",
        test_type="Validation",
        severity="Low",
    ),
    row(
        "EC-034",
        "Pagination offset negative or limit > 1000",
        "400 validation error.",
        "@Min(0) offset, @Min(1) @Max(1000) limit on list endpoints.",
        "Internal user",
        "Operations",
        test_type="Boundary",
        severity="Low",
    ),
    row(
        "EC-035",
        "Document upload unsupported file type or oversized file",
        "Rejected with clear error; checklist not updated.",
        "ConfigurableLoanDocumentStorageService — verify size/type restrictions in code.",
        "LSP UI Write",
        "Documents",
        test_type="Validation",
        severity="Medium",
    ),
    row(
        "EC-036",
        "Document download for non-existent document type",
        "404 not found.",
        "Ops KYC content endpoint per document type.",
        "Operations User",
        "Documents",
        test_type="Negative",
        severity="Low",
    ),
    row(
        "EC-037",
        "MIS report with invalid date range (end before start)",
        "Validation error or empty result.",
        "ReportAdminController parameters — verify validation.",
        "System Administrator",
        "Reporting",
        test_type="Validation",
        severity="Low",
    ),
    row(
        "EC-038",
        "Async report download before job completes",
        "409 or not ready error.",
        "Report request status machine.",
        "System Administrator",
        "Reporting",
        test_type="State machine",
        severity="Low",
    ),
    row(
        "EC-039",
        "Webhook redrive beyond maximum attempts",
        "Rejected; event stays in permanent failure.",
        "WebhookOutboxAdminController redrive limits.",
        "System Administrator",
        "Webhooks",
        test_type="Business rule",
        severity="Medium",
    ),
    row(
        "EC-040",
        "Acknowledge already-acknowledged alert",
        "Idempotent success or conflict — verify behaviour.",
        "OpsAlertController acknowledge endpoint.",
        "Operations User",
        "Alerting",
        test_type="Edge",
        severity="Low",
    ),
    row(
        "EC-041",
        "Loan list empty state",
        "UI shows empty state message; no errors.",
        "AdminEntityListPage and loan list components have empty states.",
        "Internal user",
        "UI",
        test_type="UI state",
        api_screen="/loan-applications",
        severity="Low",
    ),
    row(
        "EC-042",
        "Network failure during frontend API call",
        "User sees error toast/state; no silent failure.",
        "api-errors.ts and React Query error handling.",
        "Any UI user",
        "UI",
        test_type="Resilience",
        severity="Medium",
    ),
    row(
        "EC-043",
        "OPS_USER payment post vs backend SYSTEM_ADMIN-only controller",
        "Either OPS can post (if backend allows) or UI shows action but API returns 403.",
        "Potential mismatch: RepaymentsTab canPostRepayment includes OPS_USER; LoanApplicationOpsController POST payments may be SYSTEM_ADMIN only — requires runtime verification.",
        "Operations User",
        "Authorization",
        source="Code audit — suspected gap",
        test_type="Permission",
        severity="High",
        notes="Flagged for runtime test when approved.",
    ),
    row(
        "EC-044",
        "LSP invalidate via API client role",
        "API client can invalidate pre-disbursal loan programmatically.",
        "Controller @PreAuthorize on invalid endpoint is LSP_UI_WRITE only — API clients may be blocked. Potential PDF vs code mismatch.",
        "LSP API Client",
        "Origination",
        source="Code audit — suspected gap",
        test_type="Permission",
        severity="Medium",
        notes="PDF Workflow 14 says API invalidate; controller role annotation may differ.",
    ),
    row(
        "EC-045",
        "Processing fee deduction at disbursement (ADR 0004)",
        "Disbursement amount accounts for processing fee per ADR.",
        "docs/adr/0004-processing-fee-deduction.md — verify implementation in disbursement service.",
        "System",
        "Disbursement",
        source="ADR 0004",
        test_type="Business rule",
        severity="Medium",
    ),
    row(
        "EC-046",
        "Admin tenant data access filter cross-tenant leak",
        "Admin routes must not leak LSP tenant data incorrectly.",
        "AdminTenantDataAccessFilter.java present in security package (new file in git status).",
        "System Administrator",
        "Security",
        source="Code audit",
        test_type="Security",
        severity="Critical",
        notes="New filter — behaviour not runtime verified.",
    ),
    row(
        "EC-047",
        "Refresh token reuse after logout",
        "Refresh should fail; session terminated.",
        "RefreshTokenRepository revocation on logout.",
        "Any user",
        "Authentication",
        test_type="Security",
        severity="High",
    ),
    row(
        "EC-048",
        "Create user with duplicate username",
        "409 or validation error.",
        "AdminDirectoryService unique constraint on username.",
        "System Administrator",
        "User Admin",
        test_type="Duplicate",
        severity="Medium",
    ),
    row(
        "EC-049",
        "Password change below minimum length (12 chars)",
        "400 validation error.",
        "ChangePasswordRequest @Size(min=12, max=128).",
        "Authenticated user",
        "Authentication",
        test_type="Validation",
        severity="Medium",
    ),
    row(
        "EC-050",
        "IFSC invalid format on bank details update",
        "400 validation error.",
        "BorrowerBankDetailsRequest IFSC pattern.",
        "LSP API Client",
        "Borrower",
        test_type="Validation",
        severity="Medium",
    ),
]


def style_sheet(ws, row_count):
    header_fill = PatternFill("solid", fgColor="1F4E79")
    header_font = Font(color="FFFFFF", bold=True)
    for col, header in enumerate(HEADERS, 1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(HEADERS))}{row_count}"
    widths = [12, 42, 48, 12, 52, 18, 16, 14, 14, 28, 10, 24]
    for i, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(i)].width = w
    for r in range(2, row_count + 1):
        for c in range(1, len(HEADERS) + 1):
            ws.cell(row=r, column=c).alignment = Alignment(vertical="top", wrap_text=True)


def main():
    wb = Workbook()
    ws_uc = wb.active
    ws_uc.title = "Use Cases"
    ws_uc.append(HEADERS)
    for r in USE_CASES:
        ws_uc.append(r)
    style_sheet(ws_uc, len(USE_CASES) + 1)

    ws_ec = wb.create_sheet("Edge Cases")
    ws_ec.append(HEADERS)
    for r in EDGE_CASES:
        ws_ec.append(r)
    style_sheet(ws_ec, len(EDGE_CASES) + 1)

    wb.save(OUTPUT)
    print(f"Wrote {OUTPUT}")
    print(f"Use cases: {len(USE_CASES)}")
    print(f"Edge cases: {len(EDGE_CASES)}")
    print(f"All Pass/Fail: {NOT_TESTED}")


if __name__ == "__main__":
    main()
